a = float(input('ввод1'))
b = float(input('ввод2'))
c = input('функция')
if c == '+': print(a+b)
if c == '-': print(a-b)
if c == '*': print(a*b)
if c == '/': print(a/b)
if c == '//': print(a//b)
if c == '%': print(a%b)
if c == '**': print(a**b)